-- =============================================================================
-- Baseline: schema existente no projeto Supabase (hezxupksbntcwaxkmlmg)
-- Reconstruído a partir do catálogo do banco em 2026-09-29.
-- Objetos criados originalmente pelo SQL Editor, sem migrations.
-- Esta migration reflete o estado ATUAL, incluindo os problemas conhecidos
-- (P1..P11 em PROJETO.md). As correções vêm em migrations posteriores.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Tabelas
-- -----------------------------------------------------------------------------

create table public.users (
  id uuid not null,
  created_at timestamptz not null default now(),
  nome text not null,
  email text not null,
  telefone text,
  foto text,
  ativo boolean not null default true,
  constraint users_pkey primary key (id),
  constraint users_auth_fkey foreign key (id) references auth.users (id) on delete cascade
);

create table public.empresas (
  id bigint generated by default as identity,
  created_at timestamptz not null default now(),
  razao_social text not null,
  nome_fantasia text,
  cnpj text not null,
  email text,
  telefone text,
  endereco text,
  numero text,
  complemento text,
  bairro text,
  cidade text,
  estado text,
  cep text,
  logo text,
  ativo boolean not null default true,
  constraint empresas_pkey primary key (id),
  constraint empresas_cnpj_unique unique (cnpj)
);

create table public.empresa_usuarios (
  id bigint generated by default as identity,
  created_at timestamptz not null default now(),
  id_empresa bigint not null,
  id_usuario uuid not null,
  tipo_acesso text not null default 'tecnico',
  aprovado boolean not null default false,
  ativo boolean not null default true,
  data_aprovacao timestamptz,
  aprovado_por uuid,
  constraint empresa_usuarios_pkey primary key (id),
  constraint empresa_usuarios_unique unique (id_empresa, id_usuario),
  constraint empresa_usuarios_empresa_fkey foreign key (id_empresa) references public.empresas (id) on delete cascade,
  constraint empresa_usuarios_usuario_fkey foreign key (id_usuario) references public.users (id) on delete cascade,
  constraint empresa_usuarios_aprovado_por_fkey foreign key (aprovado_por) references public.users (id) on delete set null,
  constraint empresa_usuarios_tipo_acesso_check check (tipo_acesso = any (array['administrador', 'supervisor', 'executor']))
);

create index idx_empresa_usuarios_usuario on public.empresa_usuarios using btree (id_usuario);
create index idx_empresa_usuarios_aprovado on public.empresa_usuarios using btree (id_empresa, aprovado);

-- -----------------------------------------------------------------------------
-- Funções auxiliares de segurança (usadas nas policies)
-- -----------------------------------------------------------------------------

create or replace function public.usuario_pertence_empresa(p_id_empresa bigint)
returns boolean
language sql
stable security definer
set search_path to ''
as $function$
  select exists (
    select 1
    from public.empresa_usuarios eu
    where eu.id_empresa = p_id_empresa
      and eu.id_usuario = auth.uid()
      and eu.aprovado = true
      and eu.ativo = true
  );
$function$;

create or replace function public.usuario_admin_empresa(p_id_empresa bigint)
returns boolean
language sql
stable security definer
set search_path to ''
as $function$
  select exists (
    select 1
    from public.empresa_usuarios eu
    where eu.id_empresa = p_id_empresa
      and eu.id_usuario = auth.uid()
      and eu.tipo_acesso = 'administrador'
      and eu.aprovado = true
      and eu.ativo = true
  );
$function$;

-- -----------------------------------------------------------------------------
-- Trigger: cria perfil em public.users ao criar usuário no Auth
-- -----------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin

  insert into public.users (
    id,
    nome,
    email
  )
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'nome', ''),
    coalesce(new.email, '')
  );

  return new;

end;
$function$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- -----------------------------------------------------------------------------
-- RPCs
-- -----------------------------------------------------------------------------

create or replace function public.criar_empresa(p_razao_social text, p_nome_fantasia text, p_cnpj text)
returns json
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_usuario uuid;
  v_empresa bigint;
  v_cnpj text;
begin

  -- Usuário autenticado
  v_usuario := auth.uid();

  if v_usuario is null then
    return json_build_object(
      'success', false,
      'message', 'Usuário não autenticado.'
    );
  end if;

  -- Validação
  if trim(coalesce(p_razao_social, '')) = '' then
    return json_build_object(
      'success', false,
      'message', 'Razão social é obrigatória.'
    );
  end if;

  -- Remove pontuação do CNPJ
  v_cnpj := regexp_replace(
    coalesce(p_cnpj, ''),
    '[^0-9]',
    '',
    'g'
  );

  if length(v_cnpj) <> 14 then
    return json_build_object(
      'success', false,
      'message', 'CNPJ inválido.'
    );
  end if;

  -- Verifica se empresa já existe
  if exists (
    select 1
    from public.empresas
    where cnpj = v_cnpj
  ) then

    return json_build_object(
      'success', false,
      'message', 'Já existe uma empresa cadastrada com este CNPJ.'
    );

  end if;

  -- Cria empresa
  insert into public.empresas (
    razao_social,
    nome_fantasia,
    cnpj,
    ativo
  )
  values (
    trim(p_razao_social),
    nullif(trim(coalesce(p_nome_fantasia, '')), ''),
    v_cnpj,
    true
  )
  returning id into v_empresa;

  -- Primeiro usuário vira administrador
  insert into public.empresa_usuarios (
    id_empresa,
    id_usuario,
    tipo_acesso,
    aprovado,
    ativo,
    data_aprovacao,
    aprovado_por
  )
  values (
    v_empresa,
    v_usuario,
    'administrador',
    true,
    true,
    now(),
    v_usuario
  );

  return json_build_object(
    'success', true,
    'message', 'Empresa criada com sucesso.',
    'id_empresa', v_empresa
  );

exception

  when unique_violation then
    return json_build_object(
      'success', false,
      'message', 'Já existe uma empresa cadastrada com este CNPJ.'
    );

  when others then
    raise;

end;
$function$;

create or replace function public.solicitar_acesso_empresa(p_cnpj text)
returns json
language plpgsql
security definer
set search_path to ''
as $function$
declare

  v_usuario uuid;
  v_empresa bigint;
  v_cnpj text;

begin

  -- Usuário autenticado
  v_usuario := auth.uid();

  if v_usuario is null then
    return json_build_object(
      'success', false,
      'message', 'Usuário não autenticado.'
    );
  end if;


  -- Remove caracteres do CNPJ
  v_cnpj := regexp_replace(
    p_cnpj,
    '[^0-9]',
    '',
    'g'
  );


  -- Procura empresa
  select id
  into v_empresa
  from public.empresas
  where cnpj = v_cnpj
    and ativo = true
  limit 1;


  if v_empresa is null then

    return json_build_object(
      'success', false,
      'message', 'Empresa não encontrada.'
    );

  end if;


  -- Verifica se vínculo já existe
  if exists (
    select 1
    from public.empresa_usuarios
    where id_empresa = v_empresa
      and id_usuario = v_usuario
  ) then

    return json_build_object(
      'success', false,
      'message', 'Você já possui uma solicitação ou vínculo com esta empresa.'
    );

  end if;


  -- Cria solicitação
  insert into public.empresa_usuarios (
    id_empresa,
    id_usuario,
    tipo_acesso,
    aprovado,
    ativo
  )
  values (
    v_empresa,
    v_usuario,
    'tecnico',
    false,
    true
  );


  return json_build_object(
    'success', true,
    'message', 'Solicitação enviada. Aguarde a aprovação do administrador.'
  );

end;
$function$;

create or replace function public.listar_usuarios_empresa(p_id_empresa bigint)
returns table(
  id_usuario uuid,
  nome text,
  email text,
  tipo_acesso text,
  aprovado boolean,
  ativo boolean,
  data_solicitacao timestamptz,
  data_aprovacao timestamptz
)
language plpgsql
security definer
set search_path to ''
as $function$
begin

  -- Precisa estar autenticado
  if auth.uid() is null then
    raise exception 'Usuário não autenticado.';
  end if;

  -- Precisa ser administrador da empresa
  if not public.usuario_admin_empresa(p_id_empresa) then
    raise exception 'Você não possui permissão para visualizar os usuários desta empresa.';
  end if;

  return query

  select
    u.id,
    u.nome,
    u.email,
    eu.tipo_acesso,
    eu.aprovado,
    eu.ativo,
    eu.created_at,
    eu.data_aprovacao

  from public.empresa_usuarios eu

  inner join public.users u
    on u.id = eu.id_usuario

  where eu.id_empresa = p_id_empresa

  order by
    eu.aprovado asc,
    u.nome asc;

end;
$function$;

create or replace function public.aprovar_usuario(p_id_empresa bigint, p_id_usuario uuid, p_tipo_acesso text)
returns json
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_admin uuid;
begin

  v_admin := auth.uid();

  if v_admin is null then
    return json_build_object(
      'success', false,
      'message', 'Usuário não autenticado.'
    );
  end if;

  -- Verifica se quem está executando é administrador
  if not public.usuario_admin_empresa(p_id_empresa) then
    return json_build_object(
      'success', false,
      'message', 'Você não possui permissão para aprovar usuários.'
    );
  end if;

  -- Valida tipo de acesso
  if p_tipo_acesso not in (
    'administrador',
    'supervisor',
    'executor'
  ) then

    return json_build_object(
      'success', false,
      'message', 'Tipo de acesso inválido.'
    );

  end if;

  -- Verifica se o vínculo existe
  if not exists (
    select 1
    from public.empresa_usuarios
    where id_empresa = p_id_empresa
      and id_usuario = p_id_usuario
      and ativo = true
  ) then

    return json_build_object(
      'success', false,
      'message', 'Solicitação de acesso não encontrada.'
    );

  end if;

  -- Aprova
  update public.empresa_usuarios
  set
    aprovado = true,
    tipo_acesso = p_tipo_acesso,
    data_aprovacao = now(),
    aprovado_por = v_admin
  where id_empresa = p_id_empresa
    and id_usuario = p_id_usuario;

  return json_build_object(
    'success', true,
    'message', 'Usuário aprovado com sucesso.'
  );

end;
$function$;

create or replace function public.rejeitar_usuario(p_id_empresa bigint, p_id_usuario uuid)
returns json
language plpgsql
security definer
set search_path to ''
as $function$
begin

  if auth.uid() is null then
    return json_build_object(
      'success', false,
      'message', 'Usuário não autenticado.'
    );
  end if;

  if not public.usuario_admin_empresa(p_id_empresa) then
    return json_build_object(
      'success', false,
      'message', 'Você não possui permissão para rejeitar usuários.'
    );
  end if;

  delete from public.empresa_usuarios
  where id_empresa = p_id_empresa
    and id_usuario = p_id_usuario
    and aprovado = false;

  if not found then
    return json_build_object(
      'success', false,
      'message', 'Solicitação pendente não encontrada.'
    );
  end if;

  return json_build_object(
    'success', true,
    'message', 'Solicitação rejeitada.'
  );

end;
$function$;

-- -----------------------------------------------------------------------------
-- Permissões de execução (estado atual: PUBLIC revogado em 6 funções,
-- mas anon mantém EXECUTE em todas — ver P7)
-- -----------------------------------------------------------------------------

revoke execute on function public.usuario_pertence_empresa(bigint) from public;
revoke execute on function public.usuario_admin_empresa(bigint) from public;
revoke execute on function public.criar_empresa(text, text, text) from public;
revoke execute on function public.aprovar_usuario(bigint, uuid, text) from public;
revoke execute on function public.rejeitar_usuario(bigint, uuid) from public;
revoke execute on function public.listar_usuarios_empresa(bigint) from public;

grant execute on function public.usuario_pertence_empresa(bigint) to anon, authenticated, service_role;
grant execute on function public.usuario_admin_empresa(bigint) to anon, authenticated, service_role;
grant execute on function public.criar_empresa(text, text, text) to anon, authenticated, service_role;
grant execute on function public.aprovar_usuario(bigint, uuid, text) to anon, authenticated, service_role;
grant execute on function public.rejeitar_usuario(bigint, uuid) to anon, authenticated, service_role;
grant execute on function public.listar_usuarios_empresa(bigint) to anon, authenticated, service_role;

-- -----------------------------------------------------------------------------
-- Row Level Security
-- -----------------------------------------------------------------------------

alter table public.users enable row level security;
alter table public.empresas enable row level security;
alter table public.empresa_usuarios enable row level security;

-- users
create policy usuario_visualiza_proprio_perfil on public.users
  for select to authenticated
  using (id = auth.uid());

create policy usuario_atualiza_proprio_perfil on public.users
  for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

-- empresas
create policy usuario_visualiza_empresa on public.empresas
  for select to authenticated
  using (public.usuario_pertence_empresa(id));

create policy admin_atualiza_empresa on public.empresas
  for update to authenticated
  using (public.usuario_admin_empresa(id))
  with check (public.usuario_admin_empresa(id));

-- empresa_usuarios
create policy usuario_visualiza_proprio_vinculo on public.empresa_usuarios
  for select to authenticated
  using (id_usuario = auth.uid());

create policy admin_visualiza_usuarios_empresa on public.empresa_usuarios
  for select to authenticated
  using (public.usuario_admin_empresa(id_empresa));
